### ISSUE TITLE
organize the netedit files in subfolders (trac #2735)

### ISSUE THREAD

**Issue by behrisch** [DLR-TS/sumo#2735]
suggested subfolders
change/ (for GNEChange*), currently 10 classes
frame/ (for *Frame.cpp), currently 8 classes

Migrated from http://sumo.dlr.de/ticket/2735
```json
{
    "status": "new", 
    "changetime": "2017-01-31T20:01:51Z", 
    "description": "suggested subfolders\nchange/ (for GNEChange*), currently 10 classes\nframe/ (for *Frame.cpp), currently 8 classes\n", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1485892911860828", 
    "component": "netedit", 
    "summary": "organize the netedit files in subfolders", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2016-12-09T12:34:49Z", 
    "milestone": "1.1.0", 
    "owner": "namdre", 
    "type": "task"
}
```

**Comment by behrisch** [comment]
@palvarezlopez Do you think this is a lot of work? My impression is that half of the build time with Visual Studio is currently the netedit build because it does not parallelize since everything is in the same project. So I would like to have this solved.

**Comment by palvarezlopez** [comment]
@behrisch @namdre I think that shouldn't be a lot of works, because 50% of the works is already done:

![netedit hierarchy](https://user-images.githubusercontent.com/8238561/37456558-98ff2daa-2837-11e8-8ebc-d572b242c2b8.png)

The question is in how many projects can we divide netedit:

- netedit_dialogs
- netedit_frames
- netedit_items_netElements
- netedit_items_additionals
- netedit_items_shapes
- netedit_items_routeElements
- netedit_items_changes

**Comment by namdre** [comment]
ich würde keine Extra items Hierarchie-Ebene aufmachen und außerdem die
shapes mit den anderen additionals gruppieren (aus sumo-sicht sind shapes
auch additionals)


   - netedit_dialogs
   - netedit_frames
   - netedit_netElements
   - netedit_additionals
   - netedit_routeElements
   - netedit_changes



2018-03-15 11:02 GMT+01:00 Pablo Alvarez Lopez <notifications@github.com>:

**Comment by behrisch** [comment]
Jakob's approach seems to be easier so I would second that.

**Comment by palvarezlopez** [comment]
Finished task.
