### ISSUE TITLE
invalid link state at priority junction (trac #2944)

### ISSUE THREAD

**Issue by behrisch** [DLR-TS/sumo#2944]
the link must not respond to any other link, yet gets linkstate minor in the .net.xml

Migrated from http://sumo.dlr.de/ticket/2944
```json
{
    "status": "new", 
    "changetime": "2017-03-21T08:51:22Z", 
    "description": "the link must not respond to any other link, yet gets linkstate minor in the .net.xml", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1490086282053927", 
    "component": "net building (NETGEN, NETCONVERT)", 
    "summary": "invalid link state at priority junction", 
    "priority": "major", 
    "keywords": "", 
    "time": "2017-03-15T15:43:46Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
The problem is triggered by modeling 2-way bike path as two separate edges parallel to the main road. 
The expected right-of-way rules give priority to the straight-going bicycles (in both directions) over right-turning cars.
When the bikes are on a separate edge, that rule is not applied and the cars get priority.
