### ISSUE TITLE
make oportunities to switch from car to walking configurable

### ISSUE THREAD

**Issue by namdre** [DLR-TS/sumo#3591]
possibilities
- allow switching everywhere (on any edge that permits passenger as well as the vehicle)
- allow switching only on edges with access to a stopping place
- allow switching only on a configured subset of edges

it would be nice to have an option that allows setting the default permissibility for all edges and then customize those edges which deviate from the default with a new attribute.

**Comment by behrisch** [comment]
Due to the current router architecture switching can only happen at junctions or at edge splits (which are currently limited to bus stops and stop access points). So the following options for switching seem feasible (and could be combined):
1. on public transport stops and access points (current default)
1. on stopping places (parking)
1. on junctions with a connected edge which allows pedestrians but no cars
1. on junctions with a connected edge which allows pedestrians
1. on a configurable subset of junctions
1. on all junctions

Implementation will start with 1, 3, and 6.

**Comment by behrisch** [comment]
work continues in #3603 and #3608
