### ISSUE TITLE
netconvert erro

### ISSUE THREAD

**Issue by iamxg** [DLR-TS/sumo#3760]
Hi,
I perform the following command to generate a road network, But I face a problem. Could you let me know  how to resolve?

netconvert --osm-files memphis.osm.xml -o memphis.net.xml

Error: Cannot import network data without PROJ-Library. Please install packages proj before building sumo
Quitting (on error).

**Comment by behrisch** [comment]
It seems that your sumo was build without PROJ support. What is your platform, how did you install sumo and which version are you using?

**Comment by iamxg** [comment]
Hi,
Thank you for your reply. My OS is ubuntu 16.04. My version information is as follows. Is it right?
 
![image](https://user-images.githubusercontent.com/30093996/34724172-8d37f694-f512-11e7-8a7d-0c2faf854d84.png)

**Comment by behrisch** [comment]
It looks like you compiled sumo yourself is that right? If so, try to install all needed developer libraries
`sudo apt-get install libproj-dev libgdal-dev libxerces-c-dev libfox-1.6-dev`
and then do configure and make again.

**Comment by iamxg** [comment]
Hi,
Thanks a lot.
Yes， I have installed and build according to github steps. I will try these libraries.
Xian Guo.

**Comment by iamxg** [comment]
Hi, 
It can correctly work after I installed these libraries and recompiled it.
Thank you very much!
Best Regards,
Xian Guo.

**Comment by margarcuae** [comment]
Hello everyone,

 I had the same problem but I didn't compile sumo... I installed in this way 
`sudo apt-get install sumo sumo-tools sumo-doc`

Then I did this
`sudo apt-get install libproj-dev libgdal-dev libxerces-c-dev libfox-1.6-dev`

which actually didn't work for me, because I already have the libraries 
So I re-install like this

`sudo add-apt-repository ppa:sumo/stable`
`sudo apt-get update`
`sudo apt-get install sumo sumo-tools sumo-doc`

And finally It works for me :+1: 

I hope it helps someone :) !
