### ISSUE TITLE
Traffic Lights in Screenshots?

### ISSUE THREAD

**Issue by cipherboy** [DLR-TS/sumo#3796]
Two questions regarding traffic lights:

- Is there a way to change the scaling size of the traffic light and/or minimum minimum size? We'd like to see traffic lights at all scale levels.

- Can we change the screenshot size? Currently it seems dependent on the actual resolution of the window. If we export SVGs for our city, the time to export exceeds our simulation step size. If we export PNGs, 

On the side, can we run SUMO multithreaded / headless and export images? 

Edit: 
For context, we are using SUMO as a display for a cyber defense competition. We've deployed traffic lights to each team and we update the state of SUMO with the state of the remote traffic lights. We're currently trying to render Ames, IA in SUMO, but want to be able to see the state of these teams' lights. As red team attacks these lights, they'll go down and cause traffic pile ups; at this scale, we can see vehicles but not the state of the lights. 

Thank you for your time,

Alex

**Comment by behrisch** [comment]
1. The traffic lights are currently fixed in size but this is probably an easy adaption to src/guisim/GUILane.cpp (patches / pull requests are happily accepted :-)).

2. In the current master you can specify the screenshot size using TraCI, although this simply resizes the window which is maybe not what you want.

3. No it is not possible to run sumo headless and still have images.

I leave the ticket open for the first issue.

**Comment by behrisch** [comment]
We will solve this by scaling the lane to lane connections (which are already colored by the link state) together with the junction size. If you want to see only the enlarged connections you can still disable junction shape  drawing.
