### ISSUE TITLE
randomTrips.py - vType removed during validation

### ISSUE THREAD

**Issue by cipherboy** [DLR-TS/sumo#3797]
Passing `--vehicle-class` to `tools/randomTrips.py` results in a `vType` being written to the trip xml file. However, when `--validate` is passed, a route file is generated, but `duarouter` doesn't write the `vType` element in the XML. Thus, `route2trip.py` can't write a trip with the same `vType` element as generated by `randomTrips.py`. 

This happens when `vType` has an `id` element different from the `vClass` element. I think, according to [this wiki page](http://sumo.dlr.de/wiki/Definition_of_Vehicles,_Vehicle_Types,_and_Routes), that should be valid. However, we did have to modify `randomTrips.py` to support this. In our use case, we have different random trip variations (speed deviations, lane departures, etc.) with the same vehicle class, and thus wanted a way to distinguish them (thus different vType id fields). This was added via a `--vehicle-id` parameter which can be seen [here](https://github.com/cipherboy/sumo/commit/14263b8dd713edcedb0515126f433ab07e02a576).

Any thoughts?

Thanks,

Alex

**Comment by behrisch** [comment]
I am not quite sure whether I understand what you are trying to achieve, but here are my ideas on the process. If you want to give the vehicles a different vtype then do so by using the `--trip-attributes` option. In order to make the vehicle types known to the validating duarouter, you can add the vtype definition file as an additional file using `--additional-files`. An example of how this can be achieved is [here](https://github.com/DLR-TS/sumo/tree/master/tests/tools/trip/randomTrips/vclass_additional_file).

Maybe it is better to continue the discussion on the sumo-user mailing list, http://sumo.dlr.de/wiki/Contact

**Comment by behrisch** [comment]
If you think the solution provided does not fit your application then please reopen,
