### ISSUE TITLE
how can i reroute an electric vehicule to charging station when it's current  battery goes under 30% 

### ISSUE THREAD

**Issue by steevve** [DLR-TS/sumo#3927]

**Comment by namdre** [comment]
Hello,
this type of question should be adressed to our mailing list rather than our issue tracker (http://sumo.dlr.de/wiki/Contact). 

There is currently no code to automatically reroute electric vehicles based on their battery state. However, you can do this using TraCI by reading the battery level with your own process and modifying the route of the vehicle. See http://sumo.dlr.de/wiki/TraCI

**Comment by steevve** [comment]
thank you sir i will check
